apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: mybrokeredspace.userb
spec:
  username: userb
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encoded
  authorization:
    - addresses: ["mybrkqueueaddress", "price.stock.nyse.rht", "topic*"]
      operations: ["send", "recv"]
    - addresses: ["anycast1"]
      operations: ["send"]