apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: brokered-single-broker
  labels:
    app: enmasse
spec:
  displayName: Single Broker
  displayOrder: 0
  shortDescription: Single Broker instance
  longDescription: Single Broker plan where you can create an infinite number of queues until the system falls over.
  addressSpaceType: brokered
  infraConfigRef: default
  resourceLimits:
    broker: 1.9 
  addressPlans:
  - brokered-queue
  - brokered-topic
