apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: myspace.user3
spec:
  username: user3
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encoded
  authorization:
    - addresses: ["myqueue", "queue1", "queue2", "topic*", "mytopic", "myanycast", "mymulticast"]
      operations: ["send", "recv"]
    - addresses: ["anycast1"]
      operations: ["send"]